### ISSUE TITLE
Build cool GUI

### ISSUE THREAD

**Issue by Pocwiardo** [Pocwiardo/GeneticVSTComposer#13]
The task is to create a breathtaking GUI, which will drive all the generation process.
Things that have to be included:
- Scale (choose letter from list and name of a scale from different list)
- Fundamental note length
- Knobs for controlling the metrics values for GA generation (aggregated, we have to think about that)
- Screen MIDI keyboard, so you can click on it if you don't have keyboard yourself, and also indicate which keys serve which specific function, like in Native Instruments plugins: https://youtu.be/qRFQo3UdR4g?si=41oWSB7wUKZJwU0Z&t=143

We can also make "advanced" tab, where user will be able to change every metric parameter, as well as parameters of GA (generations, population, mutation rate, etc.)

Some plugins to be inspired:
- Synplant
- Native Instruments plugins (Playbox, Schema, basically any weird stuff with moving random things)

**Comment by Pocwiardo** [comment]
Key elements for now:
- [ ] scale
- [ ] sequence length (for now I think 1/2, 1, 2 measures to choose)
- [ ] Generation parameters from https://github.com/Pocwiardo/GeneticVSTComposer/issues/16
- [ ] Note range in octaves (i.e 3 to 5 octave)
- [ ] Slider to choose balance between speed of work and quality (I think three modes 50g 64p, 100g 128p and 200g 256p)

**Comment by Maciekxdabu** [comment]
Technically done.
Only that the sequence length has been added, but has nothing to do yet.
