### ISSUE TITLE
Test Neutone framework

### ISSUE THREAD

**Issue by Pocwiardo** [Pocwiardo/GeneticVSTComposer#2]
Run Neutone in python, configure the environment and find out how it works.

**Comment by Kliszek** [comment]
The tool itself can be used as a standalone app.
It processes audio in real time, and we get to choose the buffer size and if we want to use mono or stereo.
At the input, we get a Tensor (its shape depending on the mentioned parameters) and the values of the parameters the user chose.
We can define 4 custom parameters, and only knob parameters are available for now.
All the _magic_ must happen within a `forward` function, which has to return a modified Tensor.

The library provides an easy-to-use function to export the model into a usable `.nm` file, which can be loaded into the Neutone application.

<img width="706" alt="image" src="https://github.com/Pocwiardo/GeneticVSTComposer/assets/75401503/5507d28a-1804-49a1-9b61-c546ca5179ef">
