### ISSUE TITLE
GUI things to add

### ISSUE THREAD

**Issue by Pocwiardo** [Pocwiardo/GeneticVSTComposer#35]
- [x] mode choosing: 1. Full melody 2. Craft rhythm 3. Build melody on rhythm
- [x] toggle for snapping to scale
- [x] additional knob for pause amount

**Comment by Maciekxdabu** [comment]
Added the required elements and created a Pull request

**Comment by Pocwiardo** [comment]
- [ ] toggle for snapping to scale working just after clicking, so I can generate melody transpose it with keys, then click toggle when I want the notes to be snapped

**Comment by Maciekxdabu** [comment]
Done
